### ISSUE TITLE
should deploy config before installing package

### ISSUE THREAD

**Issue by Habbie** [PowerDNS/pdns_recursor-ansible#11]
I have both auth and recursor running on a machine, and the plan is to give them non-conflicting IP bindings. However, the recursor is installed (via apt-get in this case) before deploying the config, which means apt-get fails because the recursor is unable to bind to 127.0.0.1. If we deploy the config first I feel we could avoid some painful situations.

A similar consideration most likely applies to the auth role.

**Comment by atosatto** [comment]
Hey @Habbie, I tried to find a workaround for your issue but unfortunately the `recursor.conf.j2` template needs to know the `pdns_recursor` package version in order to properly serialize the given configuration (https://github.com/PowerDNS/pdns_recursor-ansible/blob/master/templates/recursor.conf.j2#L20)

Given the role use-cases, do you think this is actually an issue?
In that case we can try to refactor a little bit the role logic to workaround the `pdns_recursor_version` requirement in the configuration template.

**Comment by Habbie** [comment]
I imagine that not many people will run into this the way I did, so perhaps it's not a huge priority. It depends on how hard that refactor would be :)

**Comment by atosatto** [comment]
Closing the issue since it has been solved by #19.
